# Generated by Django 2.1.3 on 2019-03-29 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicao', models.DateField()),
                ('historico', models.CharField(max_length=28)),
                ('origem', models.CharField(max_length=6)),
                ('numero_documento', models.IntegerField(default=0)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('saldo_no_dia', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
