# Generated by Django 2.1.3 on 2019-04-02 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='hash',
            field=models.CharField(default='a', max_length=32),
            preserve_default=False,
        ),
    ]
