# Generated by Django 2.1.3 on 2019-04-05 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0003_coagricultor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coagricultor',
        ),
    ]
