# Generated by Django 2.1.3 on 2019-04-05 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ciclo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='PontoConvivenciaPorCiclo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciclo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.Ciclo')),
                ('ponto_convivencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.PontoConvivencia')),
            ],
        ),
        migrations.AlterField(
            model_name='coagricultor',
            name='ponto_de_convivencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.PontoConvivenciaPorCiclo'),
        ),
    ]
