# Generated by Django 2.1.3 on 2019-04-05 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_auto_20190405_1220'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoagrigultoresPorCiclo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciclo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.Ciclo')),
                ('ponto_de_convivencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.PontoConvivenciaPorCiclo')),
            ],
        ),
        migrations.RemoveField(
            model_name='coagricultor',
            name='ponto_de_convivencia',
        ),
    ]
