# Generated by Django 2.1.3 on 2019-04-05 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0003_auto_20190405_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='coagrigultoresporciclo',
            name='coagricultor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cadastro.Coagricultor'),
            preserve_default=False,
        ),
    ]
