# Generated by Django 2.1.3 on 2019-04-05 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0004_coagrigultoresporciclo_coagricultor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CoagrigultoresPorCiclo',
            new_name='CoagricultoresPorCiclo',
        ),
    ]
