# Generated by Django 2.1.3 on 2019-04-05 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0005_auto_20190405_1522'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CoagricultoresPorCiclo',
            new_name='CoagricultorPorCiclo',
        ),
    ]
