# Generated by Django 2.1.3 on 2019-04-05 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0006_auto_20190405_1538'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=28)),
            ],
        ),
        migrations.CreateModel(
            name='ProdutoPorCiclo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8)),
                ('ciclo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.Ciclo')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.Produto')),
            ],
        ),
    ]
