# Generated by Django 2.1.3 on 2019-04-05 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0007_produto_produtoporciclo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cesta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coagricultor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.CoagricultorPorCiclo')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.ProdutoPorCiclo')),
            ],
        ),
    ]
