# Generated by Django 2.1.3 on 2019-04-08 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0008_cesta'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemDaCesta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterModelOptions(
            name='coagricultor',
            options={'verbose_name_plural': 'Coagricultores'},
        ),
        migrations.AlterModelOptions(
            name='coagricultorporciclo',
            options={'verbose_name': 'Coagricultor por Ciclo', 'verbose_name_plural': 'Coagricultores por Ciclo'},
        ),
        migrations.AlterModelOptions(
            name='pontoconvivencia',
            options={'verbose_name': 'Ponto de Convivência', 'verbose_name_plural': 'Pontos de Convivência'},
        ),
        migrations.AlterModelOptions(
            name='pontoconvivenciaporciclo',
            options={'verbose_name': 'Ponto de Convivência por Ciclo', 'verbose_name_plural': 'Pontos de Convivência por Ciclo'},
        ),
        migrations.AlterModelOptions(
            name='produtoporciclo',
            options={'verbose_name': 'Produto por Ciclo', 'verbose_name_plural': 'Produtores por Ciclo'},
        ),
        migrations.RemoveField(
            model_name='cesta',
            name='produto',
        ),
        migrations.AddField(
            model_name='itemdacesta',
            name='cesta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.Cesta'),
        ),
        migrations.AddField(
            model_name='itemdacesta',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.ProdutoPorCiclo'),
        ),
    ]
