# Generated by Django 2.1.3 on 2019-04-08 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0009_auto_20190408_1142'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemdacesta',
            options={'verbose_name': 'Item da Cesta', 'verbose_name_plural': 'Itens da Cesta'},
        ),
        migrations.AlterModelOptions(
            name='produtoporciclo',
            options={'verbose_name': 'Produto por Ciclo', 'verbose_name_plural': 'Produtos por Ciclo'},
        ),
        migrations.AlterField(
            model_name='itemdacesta',
            name='cesta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='cadastro.Cesta'),
        ),
    ]
