# Generated by Django 2.1.3 on 2019-04-10 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0011_auto_20190408_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='ciclo',
            name='dia_base',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
