# Generated by Django 2.1.3 on 2019-04-15 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0012_ciclo_dia_base'),
    ]

    operations = [
        migrations.CreateModel(
            name='CestaDoMes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.PositiveSmallIntegerField(default=1)),
                ('cesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.Cesta')),
            ],
        ),
    ]
