# Generated by Django 2.1.3 on 2019-04-16 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0013_cestadomes'),
    ]

    operations = [
        migrations.AddField(
            model_name='cesta',
            name='versao',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
