# Generated by Django 2.1.3 on 2019-04-16 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0014_cesta_versao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cestadomes',
            options={'verbose_name': 'Cesta do Mês', 'verbose_name_plural': 'Cestas do Mês'},
        ),
        migrations.AddField(
            model_name='cestadomes',
            name='coagricultor',
            field=models.ForeignKey(default=31, on_delete=django.db.models.deletion.CASCADE, to='cadastro.CoagricultorPorCiclo'),
            preserve_default=False,
        ),
    ]
