# Generated by Django 2.1.3 on 2019-05-23 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0015_auto_20190416_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='ciclo',
            name='ativo',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cestadomes',
            name='coagricultor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='cadastro.CoagricultorPorCiclo'),
        ),
    ]
