# Generated by Django 2.1.3 on 2019-05-27 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0016_auto_20190523_1200'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cestadomes',
            options={},
        ),
        migrations.AlterModelOptions(
            name='itemdacesta',
            options={'verbose_name': 'Cesta do Mês', 'verbose_name_plural': 'Cestas do Mês'},
        ),
        migrations.AlterModelOptions(
            name='produtoporciclo',
            options={'ordering': ['produto__nome'], 'verbose_name': 'Produto por Ciclo', 'verbose_name_plural': 'Produtos por Ciclo'},
        ),
        migrations.AddField(
            model_name='cestadomes',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
            preserve_default=False,
        ),
    ]
