# Generated by Django 2.1.3 on 2019-05-27 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0017_auto_20190527_1300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cestadomes',
            name='valor',
        ),
        migrations.AddField(
            model_name='cesta',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
            preserve_default=False,
        ),
    ]
