# Generated by Django 2.1.3 on 2019-05-27 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0018_auto_20190527_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cesta',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
